# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mayte' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mayte
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'Stripe', '~> 11.2.0'

  pod 'react-native-safari-view', :path => '../node_modules/react-native-safari-view'

  target 'mayteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mayte-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mayte-tvOS

  target 'mayte-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
